###
GET http://localhost:3000/register
Content-Type: application/json
{
    "pseudo": "pseudo",
    "email": "fake@email.com",
    "password": "Azerty12345!"
}
###
POST http://localhost:3000/login
Content-Type: application/json
{
    "email": "test@test.com",
    "password": "Azerty12345!"
}

###
GET http://localhost:3000/players
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJJRCI6IjM2YTk5NTM5LWVkNWYtNDBmNi1hZjgzLTBjZDhkYzMyMWY2ZSIsImZ1bGxOYW1lIjoidW5kZWZpbmVkIHVuZGVmaW5lZCIsImlhdCI6MTcxNzAxMjgzOX0.VEWqjdwq_1_sKmXYc8xMwee4jD3UO-nRKEkOwf0sObQ

###
GET http://localhost:3000/players/46e89b9d-8cc6-4962-b290-e6d0b1ae61a0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJJRCI6IjM2YTk5NTM5LWVkNWYtNDBmNi1hZjgzLTBjZDhkYzMyMWY2ZSIsImZ1bGxOYW1lIjoidW5kZWZpbmVkIHVuZGVmaW5lZCIsImlhdCI6MTcxNzAxMjgzOX0.VEWqjdwq_1_sKmXYc8xMwee4jD3UO-nRKEkOwf0sObQ

###
PATCH http://loacalhost:3000/players/46e89b9d-8cc6-4962-b290-e6d0b1ae61a0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJJRCI6IjM2YTk5NTM5LWVkNWYtNDBmNi1hZjgzLTBjZDhkYzMyMWY2ZSIsImZ1bGxOYW1lIjoidW5kZWZpbmVkIHVuZGVmaW5lZCIsImlhdCI6MTcxNzAxMjgzOX0.VEWqjdwq_1_sKmXYc8xMwee4jD3UO-nRKEkOwf0sObQ
{
    "email": "random@icloud.com",
    "pseudo": "test"
}

DELETE http://localhost:3000/players/bc4a2910-1a9d-4723-b3da-4fc00667e137
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJJRCI6IjM2YTk5NTM5LWVkNWYtNDBmNi1hZjgzLTBjZDhkYzMyMWY2ZSIsImZ1bGxOYW1lIjoidW5kZWZpbmVkIHVuZGVmaW5lZCIsImlhdCI6MTcxNzAxMjgzOX0.VEWqjdwq_1_sKmXYc8xMwee4jD3UO-nRKEkOwf0sObQ


POST http://localhost:3000/game/host
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJJRCI6ImU5NmRkNDIwLWIwOWItNDNkMi1hZjRkLWQ3MmFhYjM0M2E0OSIsImZ1bGxOYW1lIjoidW5kZWZpbmVkIHVuZGVmaW5lZCIsImlhdCI6MTcxNzMxOTY3MX0.lAIH6crEUOsNoVvtrUbbtWsNd0CEHsLmKWOGtfwD2AY
{
    "player": {
        "id": "af9141e8-0efb-4119-b4b8-e365c6a432aa"
    }
}

POST http://localhost:3000/game/host
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJJRCI6ImU5NmRkNDIwLWIwOWItNDNkMi1hZjRkLWQ3MmFhYjM0M2E0OSIsImZ1bGxOYW1lIjoidW5kZWZpbmVkIHVuZGVmaW5lZCIsImlhdCI6MTcxNzMxOTY3MX0.lAIH6crEUOsNoVvtrUbbtWsNd0CEHsLmKWOGtfwD2AY
{
    "player": {
        "id": "af9141e8-0efb-4119-b4b8-e365c6a432aa"
    }
}

GET http://localhost:3000/game/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJJRCI6ImU5NmRkNDIwLWIwOWItNDNkMi1hZjRkLWQ3MmFhYjM0M2E0OSIsImZ1bGxOYW1lIjoidW5kZWZpbmVkIHVuZGVmaW5lZCIsImlhdCI6MTcxNzMxOTY3MX0.lAIH6crEUOsNoVvtrUbbtWsNd0CEHsLmKWOGtfwD2AY

POST http://localhost:3000/game/join/33685
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJJRCI6ImU5NmRkNDIwLWIwOWItNDNkMi1hZjRkLWQ3MmFhYjM0M2E0OSIsImZ1bGxOYW1lIjoidW5kZWZpbmVkIHVuZGVmaW5lZCIsImlhdCI6MTcxNzMxOTY3MX0.lAIH6crEUOsNoVvtrUbbtWsNd0CEHsLmKWOGtfwD2AY
{
    "player": {
        "id": "3b5a3ee4-bf25-4a58-a136-5e61998e0175"
    }
}

POST http://localhost:3000/game/play/33685
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJJRCI6ImU5NmRkNDIwLWIwOWItNDNkMi1hZjRkLWQ3MmFhYjM0M2E0OSIsImZ1bGxOYW1lIjoidW5kZWZpbmVkIHVuZGVmaW5lZCIsImlhdCI6MTcxNzMxOTY3MX0.lAIH6crEUOsNoVvtrUbbtWsNd0CEHsLmKWOGtfwD2AY
{
    "player": {
        "id": "af9141e8-0efb-4119-b4b8-e365c6a432aa"
    },
    "row": 0,
    "col": 0
}

